server:
  port: 9004
#  tomcat:
#    max-threads: 200
  undertow:
    worker-threads: 128
    io-threads: 16
      

# Configuration of a local Git-repo for development locally without Docker
# note that we are still using git; We just access the git-repo via file: protocol
management:
  port: 9906
  context-path: /manage  
  security:
    enabled: false

eureka:
  port: 8761
  instance:
    preferIpAddress: true
    hostname: localhost
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.port:8761}/eureka/
    registerWithEureka: true
    fetchRegistry: true

#&serverTimezone=UTC

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookdream?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: test
    driver-class-name: org.mariadb.jdbc.Driver
    tomcat:
      initial-size: 2
      validation-query: SELECT 1
      test-while-idle: true
    password: test
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


data-validation:
  len:
    id: 100
    email: 100
    nickname: 100
    oauthsite: 50
    oauthId: 1000
    image: 4096

